name: juliodejuls
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^0.8.6
  wave: ^0.2.2
  flutter_social_button: ^1.1.4
  eva_icons_flutter: ^3.1.0
  fl_chart: ^0.55.2
  syncfusion_flutter_charts: ^20.3.61
  confetti: ^0.6.0
  line_icons: ^2.0.3
  google_nav_bar: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Anta
      fonts:
        - asset: fontisi/Anta-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Lobster
      fonts:
        - asset: fontisi/Lobster-Regular.ttf
          # - asset: fonts/TrajanPro_Bold.ttf
          # weight: 700
    - family: ShadowsIntoLight
      fonts:
        - asset: fontisi/ShadowsIntoLight-Regular.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    - family: BadScript
      fonts:
        - asset: fontisi/BadScript-Regular.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    - family: Sacramento
      fonts:
        - asset: fontisi/Sacramento-Regular.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700

    - family: Tangerine
      fonts:
        - asset: fontisi/Tangerine-Regular.ttf
        - asset: fontisi/Tangerine-Bold.ttf
    #         weight: 700
    - family: Tangerine-Bold
      fonts:
        - asset: fontisi/Tangerine-Bold.ttf
    #         weight: 700
    - family: AmatiSC
      fonts:
        - asset: fontisi/AmaticSC-Regular.ttf
        - asset: fontisi/AmaticSC-Bold.ttf
    - family: BodoniModa
      fonts:
        - asset: fontisi/BodoniModa-Italic-VariableFont_opsz,wght.ttf
        - asset: fontisi/BodoniModa-VariableFont_opsz,wght.ttf
    #         weight: 700
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
